version: "3"
services:
  db:
    image: postgres
    container_name: db
    volumes:
      - /data/docker/postgresql/data:/var/lib/postgresql/data

    environment:
      POSTGRES_PASSWORD: "postgres"
      POSTGRES_HOST_AUTH_METHOD: "trust"
      PGDATA: "/var/lib/postgresql/data/pgdata"
    ports:
      - "5432:5432"

  message_broker:
    image: "rabbitmq:3.8-management-alpine"
    container_name: message_broker
    ports:
      - "15672:15672"
      - "5672:5672"
    env_file:
      - config/environment/shared_environment.env

  tasks_manager_core:
    build:
      context: "."
      dockerfile: "Dockerfile_tasks_manager_core"
    container_name: tasks_manager_core
    volumes:
      - ./volume/tasks-manager:/app
    depends_on:
      - db
      - message_broker
    tty: true
    command: rails s -b 0.0.0.0
    ports:
      - "3000:3000"
    env_file:
      - config/environment/shared_environment.env

  auth_provider:
    build:
      context: "."
      dockerfile: "Dockerfile_auth_provider"
    container_name: auth_provider
    volumes:
      - ./volume/auth-provider:/app
    depends_on:
      - db
      - message_broker
    tty: true
    command: rails s -b 0.0.0.0
    ports:
      - "3001:3000"
    env_file:
      - config/environment/shared_environment.env

  api_gateway:
    build:
      context: "."
      dockerfile: "Dockerfile_api_gateway"
    image: "ruby:2.7.0"
    container_name: api_gateway
    ports:
      - "3002:9393"
    command: shotgun config.ru -o 0.0.0.0
    env_file:
      - config/environment/shared_environment.env
    volumes:
      - ./volume/api-gateway:/app

# docker-compose build
# docker-compose up -d
# docker-compose exec tasks_manager_core rake db:create db:migrate db:seed
# docker-compose exec auth_provider rake db:create db:migrate db:seed
# docker-compose exec tasks_manager_core rspec
# localhost:3000