version: '3'
services:
  db:
    image: postgres
    container_name: db
    volumes:
      - ./config/postgres-data:/var/lib/postgresql/data

    environment:
      POSTGRES_PASSWORD: "postgres"
      POSTGRES_HOST_AUTH_METHOD: "trust"
    ports:
      - "5432:5432"


  rails:
    build:
      context: "."
      dockerfile: "Dockerfile_rails"
      cache_from:
        - edimossilva/task-manager
    image: edimossilva/task-manager
    container_name: rails
    volumes:
      - ./volume/tasks-manager:/app
    depends_on:
      - db
    environment:
      RUBYOPT: "-W:no-deprecated -W:no-experimental"
      RAILS_MASTER_KEY: "a667717bf0a47475b0582547379c816d"
    tty: true
    command: rails server -b 0
    ports:
      - "3000:3000"

# docker-compose build
# docker-compose run rails rake db:create
# docker-compose exec rails rake db:migrate
# docker-compose exec rails rake db:seed
# docker-compose exec rails rspec
# docker-compose up -d
# localhost:3000